'use client';
import {useEffect,useMemo,useState} from 'react';
import {CartesianGrid,ComposedChart,Legend,Line,ResponsiveContainer,Scatter,Tooltip,XAxis,YAxis} from 'recharts';
import {Plus,Scale,Trash2} from 'lucide-react';
import type {Baby,BabySex,GrowthMeasurement} from '@/lib/types';
import {babyName} from '@/lib/types';
import {ageInMonths,percentileLabel,weightPercentile,whoGrowthRows} from '@/lib/who-growth';
import {dayKey} from '@/lib/dates';

const input='w-full rounded-2xl border border-[#d2ded5] bg-white/90 px-4 py-3.5 text-[16px] text-[#18312b] shadow-[0_2px_8px_rgba(22,54,42,.035)] outline-none transition focus:border-[#4f977d] focus:ring-4 focus:ring-[#dcece3]';
const card='rounded-[28px] border border-white/90 bg-white/88 p-5 shadow-[0_12px_35px_rgba(28,64,49,.075)] backdrop-blur-xl';
const primary='flex min-h-13 w-full items-center justify-center rounded-2xl bg-gradient-to-br from-[#218b6b] to-[#10664e] px-5 py-3 font-semibold text-white shadow-[0_9px_22px_rgba(19,121,91,.2)] disabled:opacity-50';
const sexLabels:Record<BabySex,string>={female:'女孩',male:'男孩'};
type Props={babies:Baby[];measurements:GrowthMeasurement[];busy:boolean;onAdd:(baby:Baby,weight:string,date:string,note:string)=>Promise<boolean>;onDelete:(item:GrowthMeasurement)=>Promise<void>;onSetSex:(baby:Baby,sex:BabySex)=>Promise<void>};
type GrowthPoint={month:number;weight:number;date:string;percentile:number|null;note:string|null};
type PointShapeProps={cx?:number;cy?:number;payload?:GrowthPoint};

function formatWeight(value:number){return value.toFixed(2).replace(/0+$/,'').replace(/\.$/,'');}
function formatAge(months:number){return months<1?`${Math.max(1,Math.round(months*30.4375))} 天`:`${months.toFixed(1).replace(/\.0$/,'')} 个月`;}

export default function GrowthView({babies,measurements,busy,onAdd,onDelete,onSetSex}:Props){
 const [babyId,setBabyId]=useState(babies[0]?.id??'');const [weight,setWeight]=useState('');const [date,setDate]=useState(dayKey(new Date()));const [note,setNote]=useState('');const [selectedPoint,setSelectedPoint]=useState<GrowthPoint|null>(null);
 useEffect(()=>{if(!babies.some(b=>b.id===babyId))setBabyId(babies[0]?.id??'');},[babies,babyId]);
 const baby=babies.find(b=>b.id===babyId)||babies[0];
 const items=useMemo(()=>measurements.filter(m=>m.baby_id===baby?.id).sort((a,b)=>b.measured_at.localeCompare(a.measured_at)),[measurements,baby?.id]);
 const points=useMemo<GrowthPoint[]>(()=>baby?items.map(m=>{const month=Number(ageInMonths(baby.birthday,m.measured_at).toFixed(2));return{month,weight:Number(m.weight_kg),date:m.measured_at,percentile:baby.sex&&month<=60?weightPercentile(baby.sex,month,Number(m.weight_kg)):null,note:m.note};}).filter(p=>p.month<=60).reverse():[],[baby,items]);
 const chartMax=useMemo(()=>{if(!baby)return 3;const current=ageInMonths(baby.birthday,dayKey(new Date()));const observed=points.length?Math.max(...points.map(point=>point.month)):0;const needed=Math.max(current,observed)+1;return Math.min(60,needed<=12?Math.max(3,Math.ceil(needed)):Math.ceil(needed/6)*6);},[baby,points]);
 const rows=useMemo(()=>baby?.sex?whoGrowthRows(baby.sex,chartMax):[],[baby,chartMax]);
 const yDomain=useMemo(()=>{const values=[...rows.flatMap(row=>[row.p3,row.p97]),...points.map(point=>point.weight)];return values.length?[Math.max(0,Math.floor(Math.min(...values)-1)),Math.ceil(Math.max(...values)+1)]:[0,20];},[rows,points]);
 const pointRadius=points.length<=12?7:points.length<=30?6:5;
 const latest=items[0];const latestMonths=baby&&latest?ageInMonths(baby.birthday,latest.measured_at):null;const percentile=baby?.sex&&latest&&latestMonths!==null&&latestMonths<=60?weightPercentile(baby.sex,latestMonths,Number(latest.weight_kg)):null;
 if(!babies.length)return <div className={`${card} py-9 text-center`}><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e3efe8]"><Plus color="#13795b"/></div><p className="mt-4 text-[#62776d]">添加宝宝后即可记录生长数据。</p></div>;
 return <>
  <div className="flex gap-2 overflow-x-auto pb-1" aria-label="选择宝宝">{babies.map(b=><button key={b.id} aria-pressed={baby?.id===b.id} className={`min-h-11 shrink-0 rounded-full px-5 font-semibold ${baby?.id===b.id?'bg-[#13795b] text-white':'border border-[#dce5df] bg-white text-[#62776d]'}`} onClick={()=>{setBabyId(b.id);setSelectedPoint(null);}}>{babyName(b)}</button>)}</div>
  {!baby?.sex?<section className={card}><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e3efe8]"><Scale color="#13795b"/></div><h2 className="mt-4 text-xl font-semibold">先选择 {babyName(baby)} 的性别</h2><p className="mt-2 text-sm leading-relaxed text-[#62776d]">WHO 体重年龄标准按男孩和女孩分别计算。选择后会保存到宝宝资料中。</p><div className="mt-5 grid grid-cols-2 gap-3">{(['female','male'] as BabySex[]).map(sex=><button key={sex} className="min-h-14 rounded-2xl border border-[#13795b] bg-[#e8f2ed] font-semibold text-[#13795b]" disabled={busy} onClick={()=>onSetSex(baby,sex)}>{sexLabels[sex]}</button>)}</div></section>:<>
   <section className={card}><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-[#62776d]">{babyName(baby)} · {sexLabels[baby.sex]}</p><h2 className="mt-1 text-xl font-semibold">体重年龄百分位</h2></div>{latest&&percentile!==null?<span className="rounded-full bg-[#e3efe8] px-3 py-2 text-sm font-semibold text-[#13795b]">{percentileLabel(percentile)}</span>:null}</div>
    {latest?<div className="mt-5 flex items-end gap-2"><strong className="text-4xl tracking-tight">{Number(latest.weight_kg).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}</strong><span className="pb-1 text-[#62776d]">kg · {latest.measured_at.replaceAll('-','/')}</span></div>:<p className="mt-4 text-sm text-[#62776d]">添加第一条体重记录后，记录点会显示在曲线上。</p>}
    <div className="mt-5 h-80 w-full" role="img" aria-label={`${babyName(baby)}的体重年龄百分位曲线`}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={rows} margin={{top:12,right:8,left:-10,bottom:8}}><CartesianGrid vertical={false} stroke="#e8eee9"/><XAxis dataKey="month" type="number" domain={[0,chartMax]} tickCount={Math.min(chartMax+1,7)} allowDecimals={false} tick={{fontSize:11,fill:'#789087'}} tickLine={false} axisLine={false} unit="月"/><YAxis type="number" dataKey="weight" domain={yDomain} tick={{fontSize:11,fill:'#789087'}} tickLine={false} axisLine={false} unit="kg"/><Tooltip labelFormatter={v=>`${Number(v).toFixed(1)} 个月`} formatter={(v,n)=>[`${Number(v).toFixed(1)} kg`,n]}/><Legend wrapperStyle={{fontSize:12}}/><Line dataKey="p3" name="P3" stroke="#b8c5bd" strokeWidth={1.5} dot={false} isAnimationActive={false}/><Line dataKey="p15" name="P15" stroke="#86a293" strokeWidth={1.5} dot={false} isAnimationActive={false}/><Line dataKey="p50" name="P50" stroke="#13795b" strokeWidth={2.5} dot={false} isAnimationActive={false}/><Line dataKey="p85" name="P85" stroke="#86a293" strokeWidth={1.5} dot={false} isAnimationActive={false}/><Line dataKey="p97" name="P97" stroke="#b8c5bd" strokeWidth={1.5} dot={false} isAnimationActive={false}/><Scatter data={points} name="体重记录" fill="#e07b52" line={{stroke:'#e07b52',strokeWidth:2}} isAnimationActive={false} shape={(shapeProps:unknown)=>{const{cx=0,cy=0,payload}=shapeProps as PointShapeProps;if(!payload)return<g/>;const select=()=>setSelectedPoint(payload);return <g role="button" tabIndex={0} aria-label={`${payload.date}，${formatWeight(payload.weight)}公斤`} className="cursor-pointer outline-none" onClick={select} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select();}}}><circle cx={cx} cy={cy} r={14} fill="transparent"/><circle cx={cx} cy={cy} r={selectedPoint?.date===payload.date?pointRadius+2:pointRadius} fill="#e07b52" stroke="white" strokeWidth={3}/></g>;}}/></ComposedChart></ResponsiveContainer></div>
    {selectedPoint&&<div className="mt-3 rounded-2xl border border-[#ead9ce] bg-[#fff8f2] px-4 py-3" role="status"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-[#8d593f]">{selectedPoint.date.replaceAll('-','/')} · 月龄 {formatAge(selectedPoint.month)}</p><p className="mt-1 text-sm text-[#6f655f]">{selectedPoint.note||'体重记录'}</p></div><div className="shrink-0 text-right"><strong className="text-xl text-[#7f422b]">{formatWeight(selectedPoint.weight)} kg</strong><p className="text-sm font-semibold text-[#b15f3f]">{selectedPoint.percentile===null?'暂无百分位':percentileLabel(selectedPoint.percentile)}</p></div></div></div>}
    <p className="mt-2 text-xs leading-relaxed text-[#789087]">横轴为月龄，纵轴为体重（kg），P50 是同龄宝宝的中位数。曲线采用 WHO 0–5 岁体重年龄标准；P3–P97 为常用参考区间，单次百分位不能代替医生对连续生长趋势的判断。</p>
   </section>
   <section className={card}><h2 className="text-xl font-semibold">记录体重</h2><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-medium">体重 · kg<input className={`${input} mt-2`} type="number" inputMode="decimal" enterKeyHint="done" min="0.5" max="80" step="0.01" placeholder="例如 6.25" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label className="text-sm font-medium">测量日期<input className={`${input} mt-2`} type="date" min={baby.birthday} max={dayKey(new Date())} value={date} onChange={e=>setDate(e.target.value)}/></label></div><label className="mt-4 block text-sm font-medium">备注（可选）<input className={`${input} mt-2`} maxLength={500} placeholder="例如：体检测量" value={note} onChange={e=>setNote(e.target.value)}/></label><button className={`${primary} mt-5`} disabled={busy||!weight||!date} onClick={async()=>{if(await onAdd(baby,weight,date,note)){setWeight('');setNote('');}}}>{busy?'保存中…':'保存体重记录'}</button></section>
   <section className={card}><h2 className="text-xl font-semibold">体重记录</h2>{items.length?<div className="mt-3 divide-y divide-[#e9eee9]">{items.map(item=><div key={item.id} className="flex min-h-16 items-center gap-3 py-2"><div className="min-w-0 flex-1"><p className="font-semibold">{Number(item.weight_kg).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')} kg</p><p className="truncate text-sm text-[#789087]">{item.measured_at.replaceAll('-','/')}{item.note?` · ${item.note}`:''}</p></div><button className="flex h-11 w-11 items-center justify-center rounded-full text-[#a64c49]" aria-label={`删除 ${item.measured_at} 的体重记录`} disabled={busy} onClick={()=>onDelete(item)}><Trash2 size={18}/></button></div>)}</div>:<p className="mt-3 text-sm text-[#62776d]">还没有体重记录。</p>}</section>
  </>}
 </>;
}
